version: '2'

services:
  br2:
    image: br2-image
    container_name: br2-container
    build:
      context: ./br2
      dockerfile: Dockerfile
    volumes:
      - ./br2/build:/br2-build
      - br2-dl:/br2-dl
      - br2-ccache:/br2-ccache
      - ~/.ssh:/br2-ssh/.ssh:ro
    privileged: true
    tty: true
    user: 10000:10000
    environment:
      TZ: Asia/Tokyo
    #entrypoint: /working-br2/entry.sh

volumes:
  br2-ccache:
    external: true
  br2-dl:
    external: true
